//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSync.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSync.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć plik: {0}?.
        /// </summary>
        public static string AlertTextFileDelete {
            get {
                return ResourceManager.GetString("AlertTextFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki przesłane prawidłowo.
        /// </summary>
        public static string AlertTextFilesUploaded {
            get {
                return ResourceManager.GetString("AlertTextFilesUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się przesłać plików.
        /// </summary>
        public static string AlertTextFilesUploadError {
            get {
                return ResourceManager.GetString("AlertTextFilesUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń plik.
        /// </summary>
        public static string AlertTitleFileDelete {
            get {
                return ResourceManager.GetString("AlertTitleFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesyłanie plików.
        /// </summary>
        public static string AlertTitleFilesUpload {
            get {
                return ResourceManager.GetString("AlertTitleFilesUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatni tydzień.
        /// </summary>
        public static string DateLastWeek {
            get {
                return ResourceManager.GetString("DateLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trzy tygodnie temu.
        /// </summary>
        public static string DateThreeWeeksAgo {
            get {
                return ResourceManager.GetString("DateThreeWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzisiaj.
        /// </summary>
        public static string DateToday {
            get {
                return ResourceManager.GetString("DateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwa tygodnie temu.
        /// </summary>
        public static string DateTwoWeeksAgo {
            get {
                return ResourceManager.GetString("DateTwoWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczoraj.
        /// </summary>
        public static string DateYesterday {
            get {
                return ResourceManager.GetString("DateYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programie.
        /// </summary>
        public static string LabelAbout {
            get {
                return ResourceManager.GetString("LabelAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        public static string LabelApiKeyTitle {
            get {
                return ResourceManager.GetString("LabelApiKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosta aplikacja służąca do łątwego przesyłania plików z lub do urządzenia mobilnego..
        /// </summary>
        public static string LabelAppDescription {
            get {
                return ResourceManager.GetString("LabelAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj.
        /// </summary>
        public static string LabelBrowse {
            get {
                return ResourceManager.GetString("LabelBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzono:.
        /// </summary>
        public static string LabelCreatedTitle {
            get {
                return ResourceManager.GetString("LabelCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url bazy danych:.
        /// </summary>
        public static string LabelDatabaseUrlTitle {
            get {
                return ResourceManager.GetString("LabelDatabaseUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz.
        /// </summary>
        public static string LabelDownload {
            get {
                return ResourceManager.GetString("LabelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string LabelEmailTitle {
            get {
                return ResourceManager.GetString("LabelEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plików: {0}.
        /// </summary>
        public static string LabelFilesCount {
            get {
                return ResourceManager.GetString("LabelFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string LabelLogin {
            get {
                return ResourceManager.GetString("LabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie nieprawidłowe..
        /// </summary>
        public static string LabelLoginFailed {
            get {
                return ResourceManager.GetString("LabelLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string LabelLogout {
            get {
                return ResourceManager.GetString("LabelLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa:.
        /// </summary>
        public static string LabelNameTitle {
            get {
                return ResourceManager.GetString("LabelNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak elementów.
        /// </summary>
        public static string LabelNoItems {
            get {
                return ResourceManager.GetString("LabelNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelOK {
            get {
                return ResourceManager.GetString("LabelOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło:.
        /// </summary>
        public static string LabelPasswordTitle {
            get {
                return ResourceManager.GetString("LabelPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przetwarzanie pliku: {0}.
        /// </summary>
        public static string LabelProcessingFileFormat {
            get {
                return ResourceManager.GetString("LabelProcessingFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozmiar:.
        /// </summary>
        public static string LabelSizeTitle {
            get {
                return ResourceManager.GetString("LabelSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Bucket:.
        /// </summary>
        public static string LabelStorageBucketTitle {
            get {
                return ResourceManager.GetString("LabelStorageBucketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesyłanie plików.
        /// </summary>
        public static string LabelUploadingFileTitle {
            get {
                return ResourceManager.GetString("LabelUploadingFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie nieprawidłowe.
        /// </summary>
        public static string MessageLoginFailed {
            get {
                return ResourceManager.GetString("MessageLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się pobrać pliku.
        /// </summary>
        public static string ToastCannotDownloadFile {
            get {
                return ResourceManager.GetString("ToastCannotDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się przesłać plików.
        /// </summary>
        public static string ToastCannotUploadFiles {
            get {
                return ResourceManager.GetString("ToastCannotUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięto plik: {0}.
        /// </summary>
        public static string ToastFileDeleted {
            get {
                return ResourceManager.GetString("ToastFileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można usunąć pliku.
        /// </summary>
        public static string ToastFileDeletionError {
            get {
                return ResourceManager.GetString("ToastFileDeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesłano pliki.
        /// </summary>
        public static string ToastFilesUploaded {
            get {
                return ResourceManager.GetString("ToastFilesUploaded", resourceCulture);
            }
        }
    }
}
