//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSync.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_pl_PL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_pl_PL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSync.Client.Resources.AppResources_pl_PL", typeof(AppResources_pl_PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSync.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można usunąć pliku..
        /// </summary>
        public static string CannotDeleteFileMessage {
            get {
                return ResourceManager.GetString("CannotDeleteFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można pobrać pliku..
        /// </summary>
        public static string CannotDonwloadFileMessage {
            get {
                return ResourceManager.GetString("CannotDonwloadFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie elementów nie powiodło się. Więcej informacji znajduje się w pliku log..
        /// </summary>
        public static string FailedToLoadItemsMessage {
            get {
                return ResourceManager.GetString("FailedToLoadItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno checz usunąć plik {0}?.
        /// </summary>
        public static string FileDeleteDialogMessage {
            get {
                return ResourceManager.GetString("FileDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń plik.
        /// </summary>
        public static string FileDeleteDialogTitle {
            get {
                return ResourceManager.GetString("FileDeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik usunięty: {0}.
        /// </summary>
        public static string FileDeletedMessage {
            get {
                return ResourceManager.GetString("FileDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik(i).
        /// </summary>
        public static string FilesInfo {
            get {
                return ResourceManager.GetString("FilesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik(i).
        /// </summary>
        public static string FilesListInfoMessage {
            get {
                return ResourceManager.GetString("FilesListInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki przesłane prawidłowo.
        /// </summary>
        public static string FilesUploadedMessage {
            get {
                return ResourceManager.GetString("FilesUploadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string LabelApiKey {
            get {
                return ResourceManager.GetString("LabelApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket.
        /// </summary>
        public static string LabelBucket {
            get {
                return ResourceManager.GetString("LabelBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string LabelDatabase {
            get {
                return ResourceManager.GetString("LabelDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie nieprawidłowe..
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak elementów..
        /// </summary>
        public static string NoItemsMessage {
            get {
                return ResourceManager.GetString("NoItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSyncShellContextMenu.
        /// </summary>
        public static string ShellKeyName {
            get {
                return ResourceManager.GetString("ShellKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyśłij pliki z FileSync.
        /// </summary>
        public static string ShellMenuText {
            get {
                return ResourceManager.GetString("ShellMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string ToolTipClose {
            get {
                return ResourceManager.GetString("ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuń.
        /// </summary>
        public static string ToolTipDelete {
            get {
                return ResourceManager.GetString("ToolTipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pobierz.
        /// </summary>
        public static string ToolTipDownload {
            get {
                return ResourceManager.GetString("ToolTipDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyloguj.
        /// </summary>
        public static string ToolTipLogout {
            get {
                return ResourceManager.GetString("ToolTipLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalizuj.
        /// </summary>
        public static string ToolTipMaximize {
            get {
                return ResourceManager.GetString("ToolTipMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalizuj.
        /// </summary>
        public static string ToolTipMinimize {
            get {
                return ResourceManager.GetString("ToolTipMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to więcej informacji.
        /// </summary>
        public static string ToolTipMore {
            get {
                return ResourceManager.GetString("ToolTipMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odśwież.
        /// </summary>
        public static string ToolTipRefresh {
            get {
                return ResourceManager.GetString("ToolTipRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się przesłać plików..
        /// </summary>
        public static string UploadFailedMessage {
            get {
                return ResourceManager.GetString("UploadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przetwarzanie pliku: {0}.
        /// </summary>
        public static string UploadFilesMessage {
            get {
                return ResourceManager.GetString("UploadFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie jest zalogowany..
        /// </summary>
        public static string UserNotLoggedInMessage {
            get {
                return ResourceManager.GetString("UserNotLoggedInMessage", resourceCulture);
            }
        }
    }
}
